version: 2

jobs:

  build:

    branches:
      ignore: gh-pages

    docker:
      - image: ocaml/opam2:4.07
        environment:
          SUBSOCIA_CONFIG: .circleci/subsocia.conf
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_USER: ci
          POSTGRES_DB: ci
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run:
          name: Add opam-repo-paurkedal
          command: opam repo add paurkedal git://github.com/paurkedal/opam-repo-paurkedal.git
      - run:
          name: Pin package
          command: opam pin add -yn subsocia .
      - run:
          name: Install system dependencies
          command: |
            opam depext -y subsocia caqti-driver-postgresql
      - run:
          name: Install package
          command: |
            opam install -y --deps-only subsocia
            opam install -y caqti-driver-postgresql
      - run:
          name: Build
          command: opam config exec -- dune build @install
      - run:
          name: Initialize database for testing
          command: |
            echo $SUBSOCIA_CONFIG
            cat $SUBSOCIA_CONFIG
            opam config exec -- dune exec -- bin/command.exe db-init
      - run:
          name: Test
          command: |
            SUBSOCIA_CONFIG="$PWD/$SUBSOCIA_CONFIG"
            opam config exec -- dune runtest
