version: 2

jobs:

  build:

    branches:
      ignore: gh-pages

    docker:
      - image: ocaml/opam:debian-ocaml-4.13
        environment:
          TERM: xterm
          DATABASE_URI: postgresql://ci@localhost/ci?schema=subsocia_ci
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: ci
          POSTGRES_DB: ci
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run:
          name: Add opam-repo-paurkedal
          command: |
            opam repo add paurkedal https://github.com/paurkedal/opam-repo-paurkedal.git
      - run:
          name: Pin package
          command: |
            version=`egrep '^## v[0-9]' CHANGES.md | head -1 | sed 's/^## v\(.*\) - .*/\1/'`
            opam pin add -yn subsocia.${version} .
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get -y install postgresql-client
            opam depext -y subsocia caqti-driver-postgresql
      - run:
          name: Install package
          command: |
            opam install -y --deps-only -t subsocia
            opam install -y caqti-driver-postgresql
      - run:
          name: Build
          command: |
            opam config exec -- dune build @install
      - run:
          name: Test
          command: |
            echo "database_uri = \"${DATABASE_URI}\"" > tests/subsocia-test.conf
            opam config exec -- dune runtest
